# Docker Compose 本地开发覆盖配置
# 该文件会自动与 docker-compose.yml 合并
version: '3.8'

services:
  ai-ollama-proxy:
    # 开发模式下启用热重载（如果需要）
    # volumes:
    #   - ./src:/app/src:ro
    #   - ./dist:/app/dist
    environment:
      # 开发环境特有的环境变量
      - LOG_LEVEL=debug
      - NODE_ENV=development
    # 开发模式下可以添加更多端口映射
    # ports:
    #   - "9229:9229"  # Node.js 调试端口
    # 开发模式下的资源限制（更宽松）
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
# 本地开发时可以添加额外的服务
# services:
#   redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"
#     networks:
#       - ai-proxy-network
